### ISSUE TITLE
Pneumocat hangs after aligning with Bowtie

### ISSUE THREAD

**Issue by jacorvar** [phe-bioinformatics/PneumoCaT#14]
Hi,

when I run Pneumocat as shown below,  Pneumocat does not manage to end Bowtie2, although there are no errors. It is still running, but no output is being generated.

```
python PneumoCaT-master/PneumoCaT.py -o results -1 28_S14_L001_R1.fastq.gz -2 28_S14_L001_R2.fastq.gz -b $(which bowtie2) -t 4
```
 Btw, I use Bowtie2 and reads were qc-trimmed. If reads are not trimmed, it does not hang.

Any ideas?

Thanks

**Comment by CarmenSheppard** [comment]
Hi,

We'll need a bit more information on this one as it's very hard to know from the above what the problem is and we've not come across this and we run with qc-trimmed data.  I know you have successfully managed to run PneumoCaT on some samples so can you answer the following questions and we can try to help.

1) Is it only this particular sample that is causing the problem?
2) The samples you ran before successfully were they trimmed or not?
3) Do you get any output at all from the run (log or error files)?
4) What do you see on the screen when the software hangs?
5) Does it eventually crash out or do you have to stop the run manually?
6) Have you tried mapping this file in Bowtie alone or in software other than PneumoCaT that uses bowtie (eg. SRST2)?

Hopefully with that basis Natalie might be able to help - though she may also need to ask more specific questions.

Thanks

Carmen

**Comment by jacorvar** [comment]
Hi,
1. No, it is not only one sample, it does not work for any.
2. The samples I ran previously were not trimmed, so it seems it does not work properly with trimmed ones.
3. I get the pneumo_capsular_typing.* log files. The stderror contains only:
```
2018-12-05 18:35:48,109
Building a SMALL index
```
The stdout is bigger and attached.

[pneumo_capsular_typing.zip](https://github.com/phe-bioinformatics/PneumoCaT/files/2702788/pneumo_capsular_typing.zip)

4. The screen shows nothing  in particular.
5. It does not crash, it seems it is still running, but it does not generate more output indeed, so I must terminate it manually.
6. I have tried only Bowtie, mainly because it already worked with the raw reads.

Thanks

**Comment by CarmenSheppard** [comment]
Ok, Thanks.

When you say you tried only with Bowtie do you mean you run Bowtie on it's own on the trimmed reads and it has worked and completed mapping successfully? If so can you send the command/parameters you used for Bowtie as well. 

From the stdout file (in my very limited experience) it looks like Bowtie completes the creation of the reference database and starts the mapping but this is where the file ends so presumably no further activity.  I'm not sure if this is because PneumoCaT is waiting for a signal of Bowtie completion which doesn't happen or if Bowtie is actually not completing  (or for some reason taking anoverly extended time).  

I'm not sure I can help much further as this is outside of my experience now, and Natalie is very busy, but maybe able to help but bearing in mind the Christmas break - it may not be too quick. 

Can you send details of the program you are using to qc trim and any other information about this such as parameters used etc.

Have you tried any other qc trimming programs?

**Comment by CarmenSheppard** [comment]
No futher correspondance
