### ISSUE TITLE
How many serotypes does the current version contain? 

### ISSUE THREAD

**Issue by jacorvar** [phe-bioinformatics/PneumoCaT#15]
Hi I'd like to know how many serotypes the current version contains and how often it is updated. 

Thanks in advance

**Comment by CarmenClark** [comment]
The serotypes included are only those discussed in the original Kapatai 2014 PeerJ paper. We have only made minor changes to the CTVdb since then for some subtypes which otherwise called with ambiguous results (eg 15A+) .

We would like to update the tool and the db in the future but we have very limited resources to do so, at persent so it will be awhile before we are able to produce a major update.  Other groups have developed their own tools based on the PneumoCaT CTVdb (eg. Sanger - SeroBA) to include variants that they are interested in for their own purposes and these contain more genetic variants than our database.

 
For our purposes, as we were directly replacing a phenotypical method we kept the db mostly for the phenotypical types as described by SSI at the time of publication, this means that some newly described novel subtypes such as 35D are not yet supported in the CTVdb, though we do want to include them in the future.

**Comment by CarmenSheppard** [comment]
The serotypes included are only those discussed in the original Kapatai 2014 PeerJ paper. We have only made minor changes to the CTVdb since then for some subtypes which otherwise called with ambiguous results (eg 15A+) .

We would like to update the tool and the db in the future but we have very limited resources to do so, at present so it will be awhile before we are able to produce a major update. Other groups have developed their own tools based on the PneumoCaT CTVdb (eg. Sanger - SeroBA) to include variants that they are interested in for their own purposes and these contain more genetic variants than our database.

For our purposes, as we were directly replacing a phenotypical method we kept the db mostly for the phenotypical types as described by SSI at the time of publication, this means that some newly described novel subtypes such as 35D are not yet supported in the CTVdb, though we do want to include them in the future.
