### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bhclement** [phe-bioinformatics/PneumoCaT#16]
Hello, 

I was trying to use pneumocat but encountered an error message:

===================
$ PneumoCaT.py -1 C6_S22_L001_R1_001.fastq -2 C6_S22_L001_R2_001.fastq -o C6_pneumo -t 8

running bowtie index
There was an error in the function 'best_coverage'
____________________________________________________________

Traceback (most recent call last):

  File "/home/ctsui/.conda/envs/biotools/bin/modules/utility_functions.py", line 59, in try_and_except

    return function(*parameters, **named_parameters)

  File "/home/ctsui/.conda/envs/biotools/bin/modules/Serotype_determiner_functions.py", line 215, in best_coverage

    bamfile = pysam.Samfile(bam, "rb")

  File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4808)

  File "pysam/calignmentfile.pyx", line 533, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7027)

IOError: file `C6_pneumo/C6_S22_L001_R1_001-sorted.bam` not found

_
Is there something wrong with bowtie?

will appreciate for advice. Thanks,

**Comment by grovesn** [comment]
Hi,

This is a known issue with the filename formats that pneumocat expects. 
The filenames required by PneumoCAT are a specific format and this is why your samples cannot be mapped.
Please make sure that your filenames end with the read number.
E.g your files in the example: C6_S22_L001_R1_001.fastq
need to be changed to C6_S22_L001_**R1**.fastq

Sorry for the inconvenience - this is due to be fixed in the next version.

Thanks,
Natalie

**Comment by bhclement** [comment]
Thanks. I will try again.

**Comment by bhclement** [comment]
Hello Natalie,

The same error message appear; there are other issues?
Will appreciate for advice. Thanks,

**Comment by CarmenSheppard** [comment]
Hi.

I tried to replicate the error in case it was due to the file names, so I changed the example file (PHESPV0253)  name from the repository to the same name as you were using (without the last 001 which we know will cause problems in part 2 of the pipeline) and I also ungzipped the file as you appear to be using fastq rather than fastq.gz. PneumoCaT completed the run with no issue on our renamed and ungzipped example file so it does not appear to be due to PneumoCaT itself or the file name you are using (if you conform to the requested filename set up as specified in the readme ad remove the 001).

Can you run the example files on the repository? Have you successfully run any files?

 If you haven't already done so then please try to run [PHESPV0253 in the Example folder](https://github.com/phe-bioinformatics/PneumoCaT/tree/master/Examples/PHESPV0253) on the repository. This should give a serotype result which goes into the SNP_determination part of the script and therefore tests both parts. the other example file is resulted by mapping only (part1). The ouput xml from your run of this example sample should gives results like that given in the xml on the repository.

This example file should run without problems provided the set up of the software requirements is correct. If this file does not work then please check the software requirements and make sure that the versions of Bowtie and samtools are as stated.

If the example file runs (or other files run) but your sample file does not then it could be a problem with the quality of the input fastq.

Thanks

Carmen

**Comment by CarmenSheppard** [comment]
no further correspondance
