### ISSUE TITLE
serotype 37

### ISSUE THREAD

**Issue by gtonkinhill** [phe-bioinformatics/PneumoCaT#19]
Hi,

I noticed serotype 37 appears to be truncated in the database and was wondering why this was?

The one in the database appears to be 1555nt whilst the reference located at https://www.ncbi.nlm.nih.gov/nuccore/CR931709.1?report=fasta is 18030nt.

Thanks

**Comment by CarmenSheppard** [comment]
Hi, 

Many thanks for your comment/ question. 

The sequence used in PneumoCaT to define serotype 37 is the _tts_ gene sequence alone.  It has been shown that 37 capsular polysaccharide is produced by  a single gene which sits outside of the regular capsular operon of pneumococcus.   in serotype 37 Pneumococci there is a degraded serotype 33F-like capsular operon in the regular position but this is not required to produce the capsule, the entire syntesis is managed by the _tts_ gene.  (This is mentioned on the publication describing PneumoCaT .. Kapatai et al, PeerJ 2016 and this references other work on serotype 37 describing _tts_ and the production of serotype 37 capsule - Llull et all Exp med 1999).  

The call for serotype 37 is made only by the presence of the _tts_ gene. This means that PneumoCaT can occasionally call serotype 37 in isolates that are not pneumococcus (Sheppard et al Peerj 2017) , these lack the degraded 33F operon but _may_ still have the capacity to produce serotype 37 capsular polysaccharide.  In other related serotyping software such as SeroBA, I beleive the degraded 33F capsular operon is also searched as well as _tts_ in order to call the serotype, so it likely would not call 37 in these non-pneumococcal species.  In a future major update of PneumoCaT that we are working on we hope to be able to make the distinction between those that just contain _tts_ and those that also contain the 33F-like operon, though in our workflow we have other methods for ensuring the species ID (kmerID) so do not rely on PneumoCaT for this.

The reference FASTA you linked to is the 33F- like capsular operon sequence.

Hope this helps.

Carmen

**Comment by gtonkinhill** [comment]
Thank you very much for the quick and detailed response! That helps to clear things up.
