### ISSUE TITLE
Can Not Running PneumoCaT

### ISSUE THREAD

**Issue by noisrevni** [phe-bioinformatics/PneumoCaT#20]
I followed the "SetUpInstructions" written by Georgia Kapatai – 30th March 2018，but there are a few differences:

1. I have installed anaconda3 before, so I skipped step1;
2. Due to the Great Firewall of China, I got a clone of PneumoCaT from a mirror website of github;
3. To install PneumoCaT dependencies, I create a new environment in anaconda3:
`conda create -n pneumocat`
`conda activate pneumocat`
`conda install pysam numpy lxml yaml `
`conda install biopython `
(can not use "-c bioconda")
`conda install biopython`
(can not use "-c bioconda")

Finally, when I running the command 
`python PneumoCaT.py –i Examples/PHESPV0253`
 it showed:

> File "PneumoCaT.py", line 123
    print "Unexpected number (" + str(len(fastq_files)) + ") of fastq files. Please use options -1 and -2 to specify the path to the fastq files"
                              ^
SyntaxError: invalid syntax

![PneumoCaT error](https://user-images.githubusercontent.com/67349504/91251901-06e17580-e78f-11ea-8154-1b42d57149ab.png)

I would appreciate it if you could answer my question. Thank you very much.

ZY_Yan
PhD candidate of Clinical Laboratory Diagnostics,
West China Second University Hospital,
Sichuan University
E-mail: 307376761@qq.com

**Comment by CarmenSheppard** [comment]
Hi ZY Yan,

Thank you for contacting us. PneumoCaT currently runs in Python 2 not Python 3 so you will need to install anaconda 2 rather than anaconda 3 in order to run the software.  Hopefuly this will solve your issue.

Many thanks,

Carmen

**Comment by noisrevni** [comment]
Hi Carmen，

Thank you very much. 
I create a new environment of Python 2.7, and installed all PneumoCaT dependencies in it. 
(via the command: `conda create -n py2 python=2.7 anaconda`)
However, I can only run the command:
`python PneumoCaT.py -h`
but can not run the command:
`python PneumoCaT.py –i Examples/PHESPV0253`
or
`python PneumoCaT.py –1 Examples/PHESPV0253/PHESPV0253.1.fastq.gz -2 PHESPV0253.1.fastq.gz`
(showed 

> PneumoCaT.py: error: unrecognized arguments: –i Examples/PHESPV0253 

or 

> PneumoCaT.py:` error: unrecognized arguments: –1 Examples/PHESPV0253/PHESPV0253.1.fastq.gz

and I had rename them from "R1"/"R2" to "1/2" to fit the instructions on website)
![1](https://user-images.githubusercontent.com/67349504/91370846-fd651580-e841-11ea-844d-02ad0e9b8435.png)
![2](https://user-images.githubusercontent.com/67349504/91370852-0229c980-e842-11ea-9e0e-1a8d912d16b9.png)
![3](https://user-images.githubusercontent.com/67349504/91370856-048c2380-e842-11ea-8813-6874303fcd1c.png)


Your prompt reply will be very much appreciated. Thank you.

**Comment by noisrevni** [comment]
*Correct：`-2 PHESPV0253.1.fastq.gz` → `-2 Examples/PHESPV0253/PHESPV0253.2.fastq.gz`

![4](https://user-images.githubusercontent.com/67349504/91371915-e3790200-e844-11ea-8909-c8ebb286099f.png)

**Comment by CarmenSheppard** [comment]
Hi, 
I'm afraid I haven't been able to reproduce your issue. I tried setting up a new environment, I actually used Anaconda3 but installed python 2.7 in the new environment (sorry I should have suggested this earlier).  Using the command -i and the Examples/PHESPV0253  as you used and PneumoCaT worked.  I also realised the instructions are incorrect regarding yaml, it should be istalled as "pyyaml" not yaml as initially it did not work due to "yaml module not found" but worked after pyyaml install.

In my new environment I have the following versions, Perhaps check whether your versions match?

Name                    Version   
biopython                 1.74
bowtie2                   2.3.5.1 
lxml                      4.4.2   
numpy                     1.16.6    
pysam                     0.15.3        
python                    2.7.18    
pyyaml                    3.12  
samtools                  1.7   

Also it is not necessary to rename the example files though this should not have affected the run. Files only need to be renamed if  the name format after the 1 or 2 is different to stated in the instructions, so R1 and R2 is fine, but they have to be "*1.fastq.gz" or "*2.fastq.gz" we are working on a new version of PneumoCaT which will avoid this issue but it will not be available for a while yet.

Hope this helps
Carmen

**Comment by noisrevni** [comment]
Hello Carmen,

Thank you for your prompt reply.
I use the Ubuntu 18.04 system and have updated all the software versions in the environment to be consistent with yours.
However, when I input files, the terminal still reported errors (`unrecognized arguments`). I think it is unlikely to be an installation problem, after all, the command `python PneumoCaT.py -h` is valid. Maybe we are missing some dependencies, or there are other problems.
Do you have any other suggestions? I have more than 40 NGS data that require capsule typing, but I do lack relevant knowledge of bioinformatics. 

Looking forward to your reply.
Again, really appreciate your help.

**Comment by CarmenSheppard** [comment]
Hi there,

I think the dependencies should be fine as other wise you would end up with missing module errors etc. 

As I can't replicate the problem we wondered if it could be some kind of character mapping error. Are you copying and pasting the command or typing it in manually. If you are copying and pasting from the docs, perhaps try typing in manually?

Carmen

**Comment by noisrevni** [comment]
Hi Carmen,

Thank you for your patient explanation. I can now run the sample file normally by typing the code in manually, although I don’t know where the previous problem was :-P

Again, Thank you very much!
