### ISSUE TITLE
Need summarize a lot of results in one file

### ISSUE THREAD

**Issue by VoronDM** [phe-bioinformatics/PneumoCaT#22]
After worked with about 200-300 samples I had much subdirectories with resulting XML. Is It possible to summarize all results at one file?

**Comment by CarmenSheppard** [comment]
Hi,

yes this is an issue when running lots of samples and there is no method within PneumoCaT to summarise multiple results as it was written to be a module as part of a bigger pipeline which uses other methods to summarise and this is very specific to our particular pipeline (which PneumoCaT is part of) and wouldn't be applicable to other circumstances.

There are various xml parsing tools could be used from python for example,, but bearing in mind that, for those samples which required subtyping, it would need to find the SNP-serotyping folder and use the xml within that for final output rather than the initial one. My colleague @grovesn has some code that will help  with parsing the serotyping xmls, though it doesn't do the whole process.

I am working on a totally new version of PneumoCaT which will include a way of summarising results in one place (and also will have more user-friendly outputs than xml). However this is not ready yet and as it is a completely new version using very differnt methods and has very different outputs the collation method is not applicable to this version.
